name: troca_facil
description: Uma plataforma que facilita a troca de objetos entre utilizadores.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  flutter_local_notifications: ^15.1.0+1
  geolocator: ^10.0.0
  oauth2_client: ^3.2.1
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  firebase_storage: ^11.2.6
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/